### ISSUE TITLE
Kakuyomu Layout Changes? causing errors.

### ISSUE THREAD

**Issue by raeka21** [setsumi/Syosetu-Downloader-plus#14]
Can't update series from Kakuyomu. Will provide SS if needed.

**Comment by setsumi** [comment]
It seems they removed table of contents page and made a dynamic "thing" you have to click bit by bit to reveal instead. If there is still exist a link to the proper table of contents as before it will be a quick fix, otherwise it is not so simple. I have an idea to make browser automation emulating clicking through all that mess, but no guarantees and it will take time.
