### ISSUE TITLE
multiple history download & folder name

### ISSUE THREAD

**Issue by shirogutama** [setsumi/Syosetu-Downloader-plus#7]
Hi, I like this repo and use it frequently. Don't you think that will be great if we can add a check box on history and download updates from multiple novel titles?

Also, it will be more perfect if we can rename the Japanese title folder name with a custom title for simplicity.
thanks.

**Comment by raeka21** [comment]
I'd love to have that custom name feature a lot.

**Comment by setsumi** [comment]
Regarding custom folder name, since I don't understand clear reasons and intentions behind the request the way it should be implemented is ambiguous. Basically don't know what to do.

**Comment by raeka21** [comment]
ahhh, what reasons behind this user, who originally requested it, idk. But what I meant is that, since the novels I download are japanese, most of the time, the way I identify the novel is not by the japanese title it had. but rather by the first thing I know of its title.


and that's the thing that troubles me a lot. since it can rather be confusing sorting the thing I download. And trying to rename the folder is just.... well, kind of not what I wanted, I don't want to create duplicates of novel folders; I do not want to manually doing the sorting is what I mean here, since if I just go to file explorer and directly change the folder's title there, if I want to update the novel chapters, your app will just go and create a new novel folder with its title from the app itself, those Japanese characters. 

To put it simply, I want a feature to rename the "save to" of the novel I download. For example, right clicking the novel title in your app will show me an option to rename the title; this will change the title in the app and directory folder it goes to. 

if you're familiar with FMD2 you could see what I meant more clearly by going to favorites. There is a table-head named "save to", and right-clicking on one of the rows will give an option "Change 'save to'". In fmd2, it will not change the title but where that manga downloads goes to, and that's precisely it.

![Screenshot (78)](https://github.com/setsumi/Syosetu-Downloader-plus/assets/114666600/fea75342-5e76-45c2-ab18-b68032eae51a)

of course, what I'm asking is basically two features, the high in priority one is to rename the "save to", and the other is to rename the title in the app. But you could just do the "save to", since I'm not doing the sorting in your app, but rather, in the file explorer, if that makes it easier for you to work.
And that summed it up.

**Comment by setsumi** [comment]
I see, so renaming title along with folder should be okay. Thank you for explanation, will look into it.

**Comment by setsumi** [comment]
Implemented i think.

**Comment by raeka21** [comment]
"That folder already exist"
I think here you should let us proceed. Because I have already a novel named Tenkomori as folder with alphabets not with kanji. So when I tried to rename it in the app, it doesn't let me. Even though the end result would still be the same.

**Comment by raeka21** [comment]
welp, i just realized that not only did it renamed the title in the app, but it also renamed the novel's download folder. Good job. oh and also, crap I can't close this issue, but great work regardless!
